### PR TITLE
Touch handling framework (state machine), objects context menu with deletion

### PR DESCRIPTION
**Pull request by szelinskip**
TouchDetction framework, including:
        - TouchDetector state machine
        - UI controls handling (buttons etc.)
        - Context menu for selected object (selection done by holding)
        - Possibility to delete selected object

### CODE REVIEW

**Comment by szelinskip** [comment]
[Allow to place multiple objects](https://trello.com/c/m8XhHiyb/10-allow-to-place-multiple-objects)

**Comment by szelinskip** [comment]
[Allow to place objects relative to existing objects](https://trello.com/c/npWUELxg/11-allow-to-place-objects-relative-to-existing-objects)

**Comment by szelinskip** [comment]
[Add ability to delete objects](https://trello.com/c/niNWrcEH/8-add-ability-to-delete-objects)

**Comment by szelinskip** [comment]
[Basic UI handling](https://trello.com/c/YhKYjfd4/14-basic-ui-handling)

**Comment by szelinskip** [comment]
[TouchDetection framework](https://trello.com/c/acFSFD77/13-touchdetection-framework)

**Review by WlodekLipski — APPROVED** [review]

**Pull request merged**
